

database:
  type: mysql           # 数据库类型: mysql / postgresql / sqlite 等
  host: your_db_host    # 数据库地址，例如 localhost 或 127.0.0.1
  port: 3306            # 数据库端口，MySQL 默认 3306
  user: your_db_user    # 数据库用户名
  password: your_db_password  # 数据库密码
  database_name: your_db_name  # 数据库名
  charset: utf8mb4      # 字符集
  autocommit: true      # 是否自动提交事务
  connect_timeout: 10   # 连接超时时间（秒）
